#+title: airicbear.github.io
#+author: Eric Nguyen

This repository contains the source code for my personal website (Eric Nguyen).

* Editing

I use [[https://www.spacemacs.org][Spacemacs]] and [[https://orgmode.org][org-mode]] to publish this website via [[https://orgmode.org/manual/Publishing.html][org-publish]].
When I modify my =.org= files, I use =org-export= (bound to =C-c C-e P x=) to publish the project.
If I want to publish unmodified files, I use =eval-expression= (bound to =M-:=) and then evaluate =(org-publish "orgfiles" t)=.

When I modify my =src/org-blog.el=, I use =load-file= to redefine =org-publish-project-alist=.
Note that Emacs will not redefine variables using =defvar= or =defun= unless you use =eval-defun= (bound to =C-M-x= or =, e f=).

* Credits

I came across [[https://bitshiftcrazy.com][Kati's blog]] on Instagram which inspired me to start using org-publish.
Her "How?" section was very helpful in defining the project and indeed my project definition closely resembles hers.
I would also like to thank the various Stack Overflow answers I found, such as [[https://stackoverflow.com/questions/21258769/using-emacs-org-mode-how-to-publish-the-unchanged-files-in-a-project][this one]].
I use the file structure suggested by Ramblings from a Corner on their article, /[[https://vicarie.in/posts/blogging-with-org.html][Blogging with Org publishing]]/.
