#+title: airicbear.github.io
#+author: Eric Nguyen

This repository contains the source code for my personal website (Eric Nguyen).

* Editing

I use [[https://www.spacemacs.org][Spacemacs]] and [[https://orgmode.org][org-mode]] to publish this website via [[https://orgmode.org/manual/Publishing.html][org-publish]].
I configured Spacemacs to evaluate =src/org-blog.el= every time I open Emacs.
When I modify my =.org= files, I use =C-c C-e P x= to publish the project.
If I want to publish unmodified files, I use =M-: (org-publish "orgfiles" t)=.

When I modify my =src/org-blog.el=, I use =SPC f e R=, since I define =.(load "~/Workspace/airicbear.github.io/src/org-blog.el")= in my =~/.spacemacs= file within the =dotspacemacs/user-config= function.
Note that Emacs will not redefine variables using =defvar=.
I haven't figured out how to do that within Emacs yet, so I simply restart Emacs.

I also haven't really figured out how the sitemap settings work yet, so you'll see random navigation links sprinkled in my =archive.org=.

* Credits

I came across [[https://bitshiftcrazy.com][Kati's blog]] on Instagram which inspired me to start using org-publish.
Her "How?" section was very helpful in defining the project and indeed my project definition closely resembles hers.
I would also like to thank the various Stack Overflow answers I found, such as [[https://stackoverflow.com/questions/21258769/using-emacs-org-mode-how-to-publish-the-unchanged-files-in-a-project][this one]].
I use the file structure suggested by Ramblings from a Corner on their article, /[[https://vicarie.in/posts/blogging-with-org.html][Blogging with Org publishing]]/.
