#+options: html-postamble:nil
#+setupfile: ../main.setup
* Blog
  :PROPERTIES:
  :EXPORT_FILE_NAME: ../posts/index
  :EXPORT_OPTIONS: toc:nil num:nil
  :END:
*** [[../posts/renaming-a-user-folder-in-windows-10.html][Renaming A User Folder in Windows 10]] [2019-11-08]
*** [[../posts/termux-dwm-guide.html][Termux dwm Guide]] [2019-08-11]
* Posts
** Termux dwm Guide
   :PROPERTIES:
   :EXPORT_FILE_NAME: ../posts/termux-dwm-guide
   :EXPORT_OPTIONS: toc:2
   :EXPORT_DATE: 2019-08-11
   :END:
*** Installation

**** Apps

     - [[https://termux.com/][Termux]]
     - [[https://www.realvnc.com/en/connect/download/viewer/android/][VNC Viewer]]

**** Termux

     Within Termux, execute the following commands:

     #+begin_example
     pkg install x11-repo dwm st tigervnc
     echo "dwm &" > ~/.vnc/xstartup
     echo "export DISPLAY=\":1\"" >> ~/.bashrc
     #+end_example

     *Notes:*

     - You can replace =dwm= with your preferred window manager such as =openbox= (I tried =i3=, but it didn't work for whatever reason).
     - We install =st= terminal here, but you can use whichever terminal you prefer that is available in Termux (e.g. =aterm=, =xterm=).
     - =~/.vnc/xstartup= is the file that specifies which programs are run on startup. In this case, we tell X to run =dwm= on startup.
     - Instead of using =echo=, you can use your preferred text editor such as =nano=, =vi=, or =ed=. If your text editor isn't available, you can simply install it by executing =pkg install= and your package name (e.g. =pkg install nano=).

*** Run 

    To run dwm, you will need to start a local X server and then connect to it.
    To do so, you can execute the following in Termux:

    #+begin_example
    vncserver -localhost
    #+end_example

    When you initialize a server with =vncserver= for the first time, you'll be prompted for password setup, it's fairly straightforward.
    If you don't know what to answer for the last question just respond no.

    #+begin_example
    Would you like to enter a view-only password (y/n)? n
    #+end_example

*** Connect

    To connect to your newly hosted server, you can open the VNC Viewer app on your phone and add a new connection by pressing the circle "plus" button.
    For your address, type =127.0.0.1:= and then your port number.
    To calculate your port number, add your display number to 5900.
    In this case, we use 1 as our display number, as set in our =~/.bashrc=, so we'd write in our address form, =127.0.0.1:5901=.
    The name can be whatever you want it to be, but I simply use =Termux= for it.

    Now that you've setup your connection, you can easily connect to it through the VNC Viewer menu and entering your password.
    If you've successfully connected, congratulations!
    If you have no idea how to use dwm, you can refer to [[https://ratfactor.com/slackware/dwm/][Dave's Visual Guide to dwm]].
    Basically, =Alt+Shift+Enter= to open terminals, =Alt+Shift+c= to close windows.
    If you were unable to connect to your server, refer to [[https://wiki.termux.com/wiki/Graphical_Environment][Termux's official guide]] on setting up a graphical environment, as I may have missed something.

    *Note:* For some reason, I have trouble opening certain programs such as =mupdf=, =dmenu=, and =emacs=.
    So if you've got the same problems, then I wouldn't worry too much about it, unless you've seen it work for other people.

*** Clean up

    To kill a server (replace =1= with your server index):

    #+begin_example
    vncserver -kill :1
    #+end_example
** Renaming A User Folder in Windows 10
   :PROPERTIES:
   :EXPORT_FILE_NAME: ../posts/renaming-a-user-folder-in-windows-10
   :EXPORT_OPTIONS: toc:2
   :EXPORT_DATE: 2019-11-08
   :END:
*** Introduction
Lately, I've been using Windows 10 again and in the process of setting up my Windows 10 account, I made the mistake of including a space in my user folder name, e.g. =C:/Users/Eric Nguyen=.

At one point, it became apparent to me that this space character was breaking programs, so I decided to rename my user folder name to omit the space by following instructions I found on StackExchange: https://superuser.com/questions/890812/how-to-rename-the-user-folder-in-windows-10.
*** What I did
The first thing I did was create a new local administrator account and sign into it.
Microsoft tries really hard to obscure the fact that you can create local accounts because they want you to use your Microsoft account but basically, just go to Account Settings \to Family & other users \to Add someone else to this PC \to I don't have this person's sign-in information \to Add a user without a Microsoft account.
Next, using that account, I followed the procedure that I found on StackExchange.
To my surprise, it was fairly simple.
Essentially, all I had to do to rename my user folder name was:
1. Rename the folder using File Explorer.
2. Using the Registry Editor, I navigated to =Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList=
3. From there, I looked for the folder that had a value of my old user folder name for the =ProfileImagePath=.
4. Then, I just set the =ProfileImagePath= value to the new name that I wanted and that's it!
*** The lesson
When naming your user folder, don't include any spaces.
